name: Cypress Tests
on: [push]
env:
  CYPRESS_EMAIL: ${{ secrets.EMAIL }}
  CYPRESS_PASSWORD: ${{ secrets.PASSWORD }}
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          Install: npm install
          start: npx cypress run --reporter json
          record: true
          parallel: false
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOWTESTSTOKEN }}